coba/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('front.welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('test',function(){
    return view('layouts.master');
});

use App\Http\Controllers\WelcomeController;
Route::resource('/',WelcomeController::class);

use App\Http\Controllers\ProvinsiController;
Route::resource('provinsi',ProvinsiController::class);

use App\Http\Controllers\KotaController;
Route::resource('kota',KotaController::class);

use App\Http\Controllers\KecamatanController;
Route::resource('kecamatan',KecamatanController::class);

use App\Http\Controllers\KelurahanController;
Route::resource('kelurahan',KelurahanController::class);

use App\Http\Controllers\RwController;
Route::resource('rw',RwController::class);

use App\Http\Controllers\Kasus2Controller;
Route::resource('kasuslokal',Kasus2Controller::class);

Route::view('states-city','livewire.home');





//validasi
Route::get('/input', 'ProvinsiController@index');

Route::post('/proses', 'ProvinsiController@store');

coba/resources/views/kasuslokal/create.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Tambah Data Kasus - Kasus</div>
                <div class="card-body">
                <form action="{{route('kasuslokal.store')}}" method="POST">
                @csrf
                <div class="col">
                    <livewire:statecity />
                </div>

                <div class="form-group">
                        <label for="">Positif</label>
                        <input   value="{{@old('positif')}}" class="form-control"  name="positif">
                        @error('positif')
                      <div class="alert  alert-danger">{{$message}}</div>
                      @enderror
                      </div>

                     <div class="form-group">
                        <label for="" >Sembuh</label>
                        <input   value="{{@old('sembuh')}}" class="form-control"  name="sembuh">
                        @error('sembuh')
                      <div class="alert  alert-danger">{{$message}}</div>
                      @enderror
                     </div>

                     <div class="form-group">
                        <label for="" >Meninggal</label>
                        <input   value="{{@old('meninggal')}}" class="form-control"  name="meninggal">
                        @error('meninggal')
                      <div class="alert  alert-danger">{{$message}}</div>
                      @enderror
                    </div>

                     <div class="form-group">
                        <label for="" >Tanggal</label>
                        <input type="date"  value="{{@old('tanggal')}}" class="form-control"  name="tanggal">
                        @error('tanggal')
                      <div class="alert  alert-danger">{{$message}}</div>
                      @enderror
                     </div>
                     
                     <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Submit</button>
                        </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection

coba/resources/views/kasuslokal/edit.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Data Kasus</div>
                <div class="card">
                <div class="card-body" >
                <form  action="{{route('kasuslokal.update',$kasuslokal->id)}}" method="post">
                <input type="hidden" name="_method" value="PUT">
                    @csrf
                        <div class="row">
                              <div class="col">
                              @livewireStyles
                                  @livewireScripts
                                  @method('PUT')
                                  <div>
                                  @livewire('statecity',['selectedRw'=> $kasuslokal->id_rw,
                                  'selectedState4'=> $kasuslokal->rw->kelurahan->id_kelurahan,
                                  'selectedState3'=> $kasuslokal->rw->kelurahan->kecamatan->id_kecamatan,
                                  'selectedState2'=> $kasuslokal->rw->kelurahan->kecamatan->kota->id_kota,
                                  'selectedState'=> $kasuslokal->rw->kelurahan->kecamatan->kota->provinsi->id_provinsi])
                                  </div>
                                  </div>
                        <div class="col">
                      <div class="form-group">
                        <label for="" class="form-label">Positif</label>
                        <input  class="form-control"  name="positif" value="{{$kasuslokal->positif}}"required>
                    </div>
                     <div class="form-group">
                        <label for="" class="form-label">Sembuh</label>
                        <input  class="form-control"  name="sembuh" value="{{$kasuslokal->sembuh}}"required>
                    </div>
                     <div class="form-group">
                        <label for="" class="form-label">Meninggal</label>
                        <input  class="form-control"  name="meninggal" value="{{$kasuslokal->meninggal}}"required>
                    </div>
                     <div class="form-group">
                        <label for="" class="form-label">Tanggal</label>
                        <input type="date" class="form-control"  name="tanggal" value="{{$kasuslokal->tanggal}}"required>
                    </div>          
                        </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-block">Submit</button>
                        </div>
                </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

coba/resources/views/kasuslokal/index.blade.php
@extends('layouts.master')
@section('css')
<!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('assets/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css')}}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{{asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('assets/dist/css/adminlte.min.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
@endsection

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
        @if (session('message'))
                <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ session('message') }}
                </div>
            @elseif(session('message1'))
                <div class="alert alert-danger" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                {{ session('message1') }}
                </div>
            @endif

            <div class="card">
                <div class="card-header">{{ __('Data Kasus Local') }}
                <a href="{{route('kasuslokal.create')}}" class="float-right btn btn-outline-primary">Tambah Data</a>
            </div>

            <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                    <thead>
                     <tr class="bg-info">
                      <th scope="col">No</th>
                                            <th scope="col"><center>Lokasi</center></th>
                                            <th scope="col"><center>RW</center></th>
                                            <th scope="col"><center>Positif</center></th>
                                            <th scope="col"><center>Meninggal</center></th>
                                            <th scope="col"><center>Sembuh</center></th>
                                            <th scope="col"><center>Tanggal update</center></th>
                                            <th scope="col"><center>Action</center></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @php $no=1;
                                    @endphp
                                    @foreach($kasuslokal as $data)

                                        <tr>
                                            <th scope="row"><center>{{$no++}}</center></th>
                                            <td><center>Kelurahan : {{$data->rw->kelurahan->nama_kelurahan}}<br>
                                            Kecamatan : {{$data->rw->kelurahan->kecamatan->nama_kecamatan}}<br>
                                            Kota : {{$data->rw->kelurahan->kecamatan->kota->nama_kota}}<br>
                                            Provinsi : {{$data->rw->kelurahan->kecamatan->kota->provinsi->nama_provinsi}}</center></td>
                                            <td><center>{{$data->rw->nama_rw}}</center></td>
                                            <td><center>{{$data->positif}}</center></td>
                                            <td><center>{{$data->meninggal}}</center></td>
                                            <td><center>{{$data->sembuh}}</center></td>
                                            <td><center>{{$data->tanggal}}</center></td>
                                            <td>
                                            <form action="{{route('kasuslokal.destroy',$data->id)}}"  method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <center>  <a href="{{route('kasuslokal.show',$data->id)}}" class="btn btn-outline-success btn-sm"><i class="fa fa-eye"></a></i>
                                    <a href="{{route('kasuslokal.edit',$data->id)}}" class="btn btn-outline-primary btn-sm"><i class="fa fa-edit"></a></i>
                                    <button type="submit"  class="btn btn-outline-danger btn-sm" onclick="return confirm('Yakin Hapus?')"><i class="fa fa-trash-alt">
                                            </form>
                                        </tr>
                                    @endforeach
                            </tbody>  
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

@section('js')
<script src="{{asset('assets/plugins/datatables/jquery.dataTables.js')}}"></script>
<script src="{{asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>

<script>
  $(function () {
    $("#example1").DataTable();
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
@endsection

coba/resources/views/kasuslokal/show.blade.php
@extends('layouts.master')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"> Data</div>

                <div class="card-body">
                <form action="{{route('kasuslokal.update', $kasuslokal->id)}}" method="POST">
                @csrf
                
                <div class="mb-3">
                <label for="">RW</label>
                        <input type="text" name="id_rw" class="form-control" value="{{$kasuslokal->rw->nama_rw}}" value="{{'kasuslokal->nama_rw'}}"readonly>                
                </div>
                <div class="mb-3">
                    <label for="" class="form-label">Positif</label>
                    <input type="text" name="positif" value="{{$kasuslokal->positif}}" class="form-control" readonly>                
                </div>
                <div class="mb-3">
                    <label for="" class="form-label">Sembuh</label>
                    <input type="text" name="sembuh" value="{{$kasuslokal->sembuh}}" class="form-control" readonly>
                </div>
                <div class="mb-3">
                    <label for="" class="form-label">Meninggal</label>
                    <input type="text" name="meninggal" value="{{$kasuslokal->meninggal}}" class="form-control" readonly>
                </div>
                <a href="{{url()->previous()}}"class="btn btn-primary">Kembali</a>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection